#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ] && [ "$SKIP_BREW" != "1" ]; then
  brew bundle check >/dev/null 2>&1 || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

# Enable access to private Go modules in the Stainless staging repos
go env -w 'GOPRIVATE=github.com/stainless-sdks/*'

echo "==> Installing Go dependencies…"

go mod tidy
