#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/stainless-api/stainless-api-go,github.com/stainless-sdks/stainless-v0-go"

echo "==> Building stl"
go build ./cmd/stl
